### ISSUE TITLE
HBMon no data

### ISSUE THREAD

**Issue by nixon7606** [ShaYmez/hblink3-docker-install#2]
Fresh install on a debian 11 server. The logs reflect the hblink is working but no data on hbmon? Hbmon is assessable but no peers no data. No errors in logs. 

2023-11-03 19:33:03,868 INFO monitor.py starting up
2023-11-03 19:33:03,869 INFO

        Copyright (c) 2016, 2017, 2018, 2019
        The Regents of the K0USY Group. All rights reserved.

        Python 3 port:
        2019 Steve Miller, KC1AWV <smiller@kc1awv.net>

        HBMonitor v2 SP2ONG 2019-2022

2023-11-03 19:33:03,870 INFO ID ALIAS MAPPER: 'peer_ids.json' is current, not downloaded
2023-11-03 19:33:03,870 INFO ID ALIAS MAPPER: 'subscriber_ids.json' is current, not downloaded
2023-11-03 19:33:03,922 INFO ID ALIAS MAPPER: peer_ids dictionary is available
2023-11-03 19:33:04,729 INFO ID ALIAS MAPPER: subscriber_ids dictionary is available
2023-11-03 19:33:04,729 INFO ID ALIAS MAPPER: talkgroup_ids dictionary is available
2023-11-03 19:33:04,730 INFO ID ALIAS MAPPER: local_subscriber_ids added to subscriber_ids dictionary
2023-11-03 19:33:04,730 INFO ID ALIAS MAPPER: local_talkgroup_ids added to talkgroup_ids dictionary
2023-11-03 19:33:04,730 INFO ID ALIAS MAPPER: local_peer_ids added peer_ids dictionary
2023-11-03 19:33:04,849 INFO reportClient object for connecting to HBlink.py created at: <__main__.reportClientFactory object at 0x7f9e409a6370>
2023-11-03 19:33:04,850 INFO Initiating Connection to Server.
2023-11-03 19:33:04,852 INFO Connected.
2023-11-03 19:33:04,852 INFO Resetting reconnection delay

**Comment by nixon7606** [comment]
That is the error

2023-11-03 19:18:50,546 INFO monitor.py starting up
2023-11-03 19:18:50,546 INFO

        Copyright (c) 2016, 2017, 2018, 2019
        The Regents of the K0USY Group. All rights reserved.

        Python 3 port:
        2019 Steve Miller, KC1AWV <smiller@kc1awv.net>

        HBMonitor v2 SP2ONG 2019-2022


2023-11-03 19:18:50,547 INFO ID ALIAS MAPPER: 'peer_ids.json' is current, not downloaded
2023-11-03 19:18:50,548 INFO ID ALIAS MAPPER: 'subscriber_ids.json' is current, not downloaded
2023-11-03 19:18:50,602 INFO ID ALIAS MAPPER: peer_ids dictionary is available
2023-11-03 19:18:51,407 INFO ID ALIAS MAPPER: subscriber_ids dictionary is available
2023-11-03 19:18:51,408 INFO ID ALIAS MAPPER: talkgroup_ids dictionary is available
2023-11-03 19:18:51,408 INFO ID ALIAS MAPPER: local_subscriber_ids added to subscriber_ids dictionary
2023-11-03 19:18:51,408 INFO ID ALIAS MAPPER: local_talkgroup_ids added to talkgroup_ids dictionary
2023-11-03 19:18:51,408 INFO ID ALIAS MAPPER: local_peer_ids added peer_ids dictionary
2023-11-03 19:18:51,523 INFO reportClient object for connecting to HBlink.py created at: <__main__.reportClientFactory object at 0x7f97bc9850d0>
2023-11-03 19:18:51,524 INFO Initiating Connection to Server.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/twisted/internet/tcp.py", line 1334, in startListening
    skt.bind(addr)
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/HBMonv2/monitor.py", line 1065, in <module>
    reactor.listenTCP(9000, dashboard_server)
  File "/usr/local/lib/python3.9/dist-packages/twisted/internet/posixbase.py", line 364, in listenTCP
    p.startListening()
  File "/usr/local/lib/python3.9/dist-packages/twisted/internet/tcp.py", line 1336, in startListening
    raise CannotListenError(self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on any:9000: [Errno 98] Address already in use.

**Comment by ShaYmez** [comment]
As the error suggests. Port 9000 is in use on your server. Find out what else is using the port or if it’s been mapped correctly on your system. The websocket port.  Sent from my iPhoneOn 4 Nov 2023, at 01:24, nixon7606 ***@***.***> wrote:﻿
That is the error
2023-11-03 19:18:50,546 INFO monitor.py starting up
2023-11-03 19:18:50,546 INFO
    Copyright (c) 2016, 2017, 2018, 2019
    The Regents of the K0USY Group. All rights reserved.

    Python 3 port:
    2019 Steve Miller, KC1AWV ***@***.***>

    HBMonitor v2 SP2ONG 2019-2022

2023-11-03 19:18:50,547 INFO ID ALIAS MAPPER: 'peer_ids.json' is current, not downloaded
2023-11-03 19:18:50,548 INFO ID ALIAS MAPPER: 'subscriber_ids.json' is current, not downloaded
2023-11-03 19:18:50,602 INFO ID ALIAS MAPPER: peer_ids dictionary is available
2023-11-03 19:18:51,407 INFO ID ALIAS MAPPER: subscriber_ids dictionary is available
2023-11-03 19:18:51,408 INFO ID ALIAS MAPPER: talkgroup_ids dictionary is available
2023-11-03 19:18:51,408 INFO ID ALIAS MAPPER: local_subscriber_ids added to subscriber_ids dictionary
2023-11-03 19:18:51,408 INFO ID ALIAS MAPPER: local_talkgroup_ids added to talkgroup_ids dictionary
2023-11-03 19:18:51,408 INFO ID ALIAS MAPPER: local_peer_ids added peer_ids dictionary
2023-11-03 19:18:51,523 INFO reportClient object for connecting to HBlink.py created at: <main.reportClientFactory object at 0x7f97bc9850d0>
2023-11-03 19:18:51,524 INFO Initiating Connection to Server.
Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/twisted/internet/tcp.py", line 1334, in startListening
skt.bind(addr)
OSError: [Errno 98] Address already in use
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/opt/HBMonv2/monitor.py", line 1065, in 
reactor.listenTCP(9000, dashboard_server)
File "/usr/local/lib/python3.9/dist-packages/twisted/internet/posixbase.py", line 364, in listenTCP
p.startListening()
File "/usr/local/lib/python3.9/dist-packages/twisted/internet/tcp.py", line 1336, in startListening
raise CannotListenError(self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on any:9000: [Errno 98] Address already in use.

**Comment by nixon7606** [comment]
I was reading your other comments and ran monitor.py by its self. The port was in use because hbmon was already running. 
Thank you for replying So quickly. 

This is the setting in hblink.cfg
[REPORTS]
REPORT: True
REPORT_INTERVAL: 30
REPORT_PORT: 4321
REPORT_CLIENTS: *

This is the setting in dashboard config
ONFIG_INC      = True                           # Include HBlink stats
HOMEBREW_INC    = True                           # Display Homebrew Peers status
LASTHEARD_INC   = True                           # Display lastheard table on main page
BRIDGES_INC     = False                          # Display Bridge status and button
EMPTY_MASTERS   = False                         # Display Enable (True) or DISABLE (False) empty masters in status
HBLINK_IP       = '127.0.0.1'                      # HBlink's IP Address
HBLINK_PORT     = 4321                           # HBlink's TCP reporting socket
FREQUENCY       = 10                             # Frequency to push updates to web clients
CLIENT_TIMEOUT  = 0                              # Clients are timed out after this many seconds, 0 to disable

The port shows up a listing
dockerd    479     root  138u  IPv4  19970      0t0  TCP *:4321 (LISTEN)


hbmon doesn't seem to be able to communicate with hblink

**Comment by nixon7606** [comment]
I am getting LastHeard data in the dashboard but nothing in Peers or Monitor. No call log

**Comment by ShaYmez** [comment]
Hi, ok I’ll take a look this evening to see if there’s any changes and update the installer. Don’t worry we will get to the bottom of the error :) On 4 Nov 2023, at 03:50, nixon7606 ***@***.***> wrote:﻿
I am getting LastHeard data in the dashboard but nothing in Peers or Monitor. No call log

**Comment by nixon7606** [comment]
Hey, Were you able to replicate the issue?

**Comment by ShaYmez** [comment]
HBMonv2 is now depreciated. I will be upgrading the monitor to a usable version that uses current libs,

**Comment by ShaYmez** [comment]
I've fixed the installer and re-compiled HBMonv2. This installer currently is fully tested on debian 10 / 11. Debian 12 has been tested but some contriants with python pip. Stability is retained on debian 11.
